[edoc-mailer] MOD: Allow to specify document requirement (for sending) [xps-index] FIX: Minor bug fix [xps-id2pdf] FIX: Minor bug fix

diff --git a/misc/edoc-mailer b/misc/edoc-mailer
--- a/misc/edoc-mailer
+++ b/misc/edoc-mailer
@@ -27,6 +27,9 @@ OPTIONS:
   -n1           First document name
   ...           ...
   -n5           Fifth document name
+  -r1           First document required (for sending)
+  ...           ...
+  -r5           Fifth document required (for sending)
   --            Treat all subsequent options as 'mutt' options
 EOF
 
@@ -39,6 +42,7 @@ MY_SUFFIX='.pdf'
 for my_dir in {1..5}; do
   MY_DIR[${my_dir}]=
   MY_NAME[${my_dir}]=
+  MY_REQD[${my_dir}]=
 done
 while [ -n "${1}" ]; do
   case "${1}" in
@@ -61,6 +65,10 @@ while [ -n "${1}" ]; do
     -n1|-n2|-n3|-n4|-n5)
       my_dir=${1#-n}
       shift; MY_NAME[${my_dir}]="${1}"
+      ;;
+    -r1|-r2|-r3|-r4|-r5)
+      my_dir=${1#-r}
+      MY_REQD[${my_dir}]='yes'
       ;;
     --)
       shift; break
@@ -121,10 +129,19 @@ IFS=$'\n'; for my_rcpt in $(cat "${MY_RCPT}"); do
   my_rcpt_id=${my_rcpt%|*}
   my_rcpt_email=${my_rcpt#*|}
   my_rcpt_files=
+  my_rcpt_skip=
   echo "INFO: Sending documents to '${my_rcpt_email}' (${my_rcpt_id})"
   for my_dir in $(echo -e ${MY_DIRS}); do
     my_file="${MY_DIR[${my_dir}]%%/}/${MY_PREFIX}${my_rcpt_id}${MY_SUFFIX}"
-    [ ! -e "${my_file}" ] && echo "WARNING: No matching file found (${my_file})" >&2 && continue
+    if [ ! -e "${my_file}" ]; then
+      echo "WARNING: No matching file found (${my_file})" >&2
+      if [ -n "${MY_REQD[${my_dir}]}" ]; then
+        echo "WARNING: File is required for sending; skipping recipient" >&2
+        my_rcpt_skip='yes'
+        break
+      fi
+      continue
+    fi
     [ ! -r "${my_file}" ] && echo "ERROR: Unreadable file (${my_file})" >&2 && continue
     if [ -n "${MY_NAME[${my_dir}]}" ]; then
       cp -p "${my_file}" "${MY_TMPDIR}/${MY_NAME[${my_dir}]}"
@@ -133,6 +150,7 @@ IFS=$'\n'; for my_rcpt in $(cat "${MY_RCPT}"); do
     fi
     my_rcpt_files="${my_rcpt_files}${my_rcpt_files:+ }'${my_file}'"
   done
+  [ -n "${my_rcpt_skip}" ] && continue
   eval mutt -s "'${MY_SUBJECT}'" "$@" ${my_rcpt_files:+-a} ${my_rcpt_files} ${my_rcpt_files:+--} ${my_rcpt_email} < "${MY_BODY}"
 done
 
