[dns-make-in-addr.arpa] NEW: Generate IPv4 reverse lookup zone [dns-make-ip6.arpa] NEW: Generate IPv6 reverse lookup zone [kvm-helper] FIX: Minor bug fixes [xps-id2pdf] FIX: Improved processing messages [edoc-mailer] FIX: Allow to specify document(s) prefix/suffix

diff --git a/misc/xps-id2pdf b/misc/xps-id2pdf
--- a/misc/xps-id2pdf
+++ b/misc/xps-id2pdf
@@ -72,58 +72,55 @@ done
 
 
 ## Process XPS file
-if [ -n "${MY_XPS}" ]; then
-  echo "INFO: processing '${MY_XPS}'"
-  my_index="${MY_DIR}/${MY_XPS##*/}.index"
-  if [ ! -e "${my_index}" ]; then
-    xps-index --frame ${MY_FRAME_Xmin} ${MY_FRAME_Ymin} ${MY_FRAME_Xmax} ${MY_FRAME_Ymax} "${MY_XPS}" > "${my_index}"
-    join -t':' -e'%NOID%' \
-      <(awk -F'|' "{ if( \$6~\"${MY_TAG}\" ) print \$1\".\"\$2 }" "${my_index}") \
-      <(awk -F'|' '{ print $1"."$2":"$6 }' "${my_index}" | sed "s|${MY_TAG}||g") \
-      | fgrep -v '%NOID%' \
-      > "${my_index}.tmp"
-    join -t ':' -v 1 \
-      <(awk -F'|' '{ print $1"."$2}' "${my_index}" | sort) \
-      <(awk -F':' '{ print $1}' "${my_index}.tmp" | sort) \
-      | sort -n -t'.' -k1,1 -k2,2 \
-      > "${my_index}.invalid"
-    if [ -s "${my_index}.invalid" ]; then
-      echo 'WARNING: The following documents/pages have no identifier:' >&2
-      cat "${my_index}.invalid" >&2
-    else
-      rm "${my_index}.invalid"
-    fi
-    mv "${my_index}.tmp" "${my_index}"
-  fi
-  my_proc_id=
-  my_proc_doc=
-  my_proc_start=
-  my_proc_stop=
-  IFS=$'\n'; for index in $(cat "${my_index}") '%END%'; do
-    my_cur_id=${index#*:}
-    [ -n "${MY_ID}" -a "${my_cur_id}" != "${MY_ID}" ] && continue
-    my_cur_index=${index%:*}
-    my_cur_doc=${my_cur_index%.*}
-    my_cur_page=${my_cur_index#*.}
-    if [ "${my_cur_doc}" == "${my_proc_doc}" -a "${my_cur_id}" == "${my_proc_id}" ]; then
-      my_proc_stop=${my_cur_page}
-    else
-      if [ -n "${my_proc_id}" ]; then
-        my_pdf="${MY_DIR}/${my_proc_doc}-${my_proc_id}.pdf"
-        if [ ! -e "${my_pdf}" ]; then
-          echo "INFO: Exporting document ${my_proc_doc} for identifier '${my_proc_id}'"
-          xpstopdf -d ${my_proc_doc} -f ${my_proc_start} -l ${my_proc_stop} "${MY_XPS}" "${my_pdf}"
-          if [ -z "$(pdftotext "${my_pdf}" - | egrep "${MY_TAG}\s*${my_proc_id}(\W|\$)")" ]; then
-            echo "ERROR: Failed to verify identifier" >&2
-            rm -f "${my_pdf}"
-          fi
+echo "INFO: processing '${MY_XPS}'"
+my_index="${MY_DIR}/${MY_XPS##*/}.index"
+if [ ! -e "${my_index}" ]; then
+  xps-index --frame ${MY_FRAME_Xmin} ${MY_FRAME_Ymin} ${MY_FRAME_Xmax} ${MY_FRAME_Ymax} "${MY_XPS}" > "${my_index}"
+  join -t':' -e'%NOID%' \
+    <(awk -F'|' "{ if( \$6~\"${MY_TAG}\" ) print \$1\".\"\$2 }" "${my_index}") \
+    <(awk -F'|' '{ print $1"."$2":"$6 }' "${my_index}" | sed "s|${MY_TAG}||g") \
+    | fgrep -v '%NOID%' \
+    > "${my_index}.tmp"
+  join -t ':' -v 1 \
+    <(awk -F'|' '{ print $1"."$2}' "${my_index}" | sort) \
+    <(awk -F':' '{ print $1}' "${my_index}.tmp" | sort) \
+    | sort -n -t'.' -k1,1 -k2,2 \
+    > "${my_index}.invalid"
+  mv "${my_index}.tmp" "${my_index}"
+fi
+my_proc_id=
+my_proc_doc=
+my_proc_start=
+my_proc_stop=
+IFS=$'\n'; for index in $(cat "${my_index}") '%END%'; do
+  my_cur_id=${index#*:}
+  [ -n "${MY_ID}" -a "${my_cur_id}" != "${MY_ID}" ] && continue
+  my_cur_index=${index%:*}
+  my_cur_doc=${my_cur_index%.*}
+  my_cur_page=${my_cur_index#*.}
+  if [ "${my_cur_doc}" == "${my_proc_doc}" -a "${my_cur_id}" == "${my_proc_id}" ]; then
+    my_proc_stop=${my_cur_page}
+  else
+    if [ -n "${my_proc_id}" ]; then
+      my_pdf="${MY_DIR}/${my_proc_doc}-${my_proc_id}.pdf"
+      if [ ! -e "${my_pdf}" ]; then
+        echo "INFO: Exporting document/pages ${my_proc_doc}.${my_proc_start}-${my_proc_stop} ($(( ${my_proc_stop}-${my_proc_start}+1 ))) for identifier '${my_proc_id}'"
+        xpstopdf -d ${my_proc_doc} -f ${my_proc_start} -l ${my_proc_stop} "${MY_XPS}" "${my_pdf}"
+        if [ -z "$(pdftotext "${my_pdf}" - | egrep "${MY_TAG}\s*${my_proc_id}(\W|\$)")" ]; then
+          echo "ERROR: Failed to verify identifier" >&2
+          rm -f "${my_pdf}"
         fi
       fi
-      my_proc_id=${my_cur_id}
-      my_proc_doc=${my_cur_doc}
-      my_proc_start=${my_cur_page}
-      my_proc_stop=${my_cur_page}
     fi
-  done
+    my_proc_id=${my_cur_id}
+    my_proc_doc=${my_cur_doc}
+    my_proc_start=${my_cur_page}
+    my_proc_stop=${my_cur_page}
+  fi
+done
+if [ -s "${my_index}.invalid" ]; then
+  sed 's/^/WARNING: Document\/page /;s/$/ has no valid identifier/' "${my_index}.invalid" >&2
+else
+  rm "${my_index}.invalid"
 fi
 
diff --git a/system/kvm-helper b/system/kvm-helper
--- a/system/kvm-helper
+++ b/system/kvm-helper
@@ -108,7 +108,13 @@ case "${MY_MODE}" in
     [ $# -lt 2 ] && echo "ERROR: Missing argument(s)" >&2 && exit 1;
     MY_HD="${1}"; shift
     MY_HOSTNAME="${1}"; shift
-    MY_OPTION_RESOURCE='-option-rom /usr/share/kvm/pxe-virtio.bin'
+    if [ -e '/usr/share/kvm/pxe-virtio.bin' ]; then
+      MY_OPTION_RESOURCE='-option-rom /usr/share/kvm/pxe-virtio.bin'
+    elif [ -e '/usr/share/qemu/pxe-virtio.rom' ]; then
+      MY_OPTION_RESOURCE='-option-rom /usr/share/qemu/pxe-virtio.rom'
+    else
+      echo "ERROR: Missing 'pxe-virtio.bin' file" && exit 1
+    fi
     MY_OPTION_BOOT='-boot n -no-reboot'
     ;;
 
@@ -148,7 +154,7 @@ if [ -n "${MY_HOSTNAME}" ]; then
   if [ -n "$(echo "${MY_HOSTNAME}" | egrep '^[0-9]{2,3}(\.[0-9]{1,3}){3}$')" ]; then
     MY_IPADDRESS="${MY_HOSTNAME}"
   else
-    MY_DNSLOOKUP="$(getent hosts ${MY_HOSTNAME} | head -n 1)"
+    MY_DNSLOOKUP="$(getent ahosts ${MY_HOSTNAME} | egrep '^[0-9]{2,3}(\.[0-9]{1,3}){3}\s{1,}STREAM'| head -n 1)"
     [ -z "${MY_DNSLOOKUP}" ] && echo "ERROR: No matching DNS entry for the given hostname (${MY_HOSTNAME})" >&2 && exit 1
     MY_IPADDRESS="$(echo "${MY_DNSLOOKUP}" | awk '{print $1}')"
     [ -z "$(echo "${MY_IPADDRESS}" | egrep '^[0-9]{2,3}(\.[0-9]{1,3}){3}$')" ] && echo "ERROR: Invalid IP address (${MY_IPADDRESS})" >&2 && exit 1
