[dircksum] MOD: Version 2. File can now be renamed without invalidating the directory checksum

diff --git a/system/dircksum b/system/dircksum
--- a/system/dircksum
+++ b/system/dircksum
@@ -10,32 +10,29 @@ SYSNOPSIS:
   directory.
 
 OPTIONS:
-  -v, --verbose
+  -V, --verbose
     Display computing progress (on 'stdout').
 
-  -s, --silent
+  -S, --silent
     Display only warnings and errors (on 'stderr').
 
-  -t, --trust
-    Trust and use existing checksums ('.dircksum' contents) without verification
-    (existing checksums will not be compared to the re-computed checksums).
-    This mode is useful to complete an interrupted checksumming.
-    WARNING: If the corresponding directory has become corrupted, it will NOT
-             be detected!
+  -c, --create
+    Create missing checksum files.
 
-  -r, --read-only
-    Perform a read-only checksum verification, without saving new/missing
-    checksums.
-
-  -p, --print
-    Print checksum results to 'stdout'
-    (useful - along with 'diff' - to detect discrepancies location).
+  -v, --verify
+    Verify existing checksum files.
 
   -d, --delete
-    Delete the checksum file from the given directory and all the parent arbo-
+    Delete the checksum file from the given directory and all its parent arbo-
     rescence.
-    This command is useful when a directory has been modified and its checksum
-    must be computed again (using the 'trust' mode).
+
+  -dd, --delete-all
+    Delete the checksum file from the given directory and both its parent and
+    children arborescence.
+
+  -p, --print
+    Print computed checksum results to 'stdout'
+    (useful - along with 'diff' - to detect discrepancies location).
 
 AUTHOR:
   Cedric Dufour - http://cedric.dufour.name
@@ -45,10 +42,11 @@ EOF
 EXIT=0
 VERBOSE=
 SILENT=
-TRUST=
-READONLY=
-PRINT=
+CREATE=
+VERIFY=
 DELETE=
+PRINT=
+VERSION='2'
 
 # Checks
 [ -z "$(which cksum)" ] && echo 'ERROR: Missing checksumming binary (cksum)' >&2 && exit 2
@@ -82,28 +80,35 @@ function _dircksum {
 
   # ... recurse sub-directories
   local __subdir
-  for __subdir in $(find "${DIRECTORY}" -mindepth 1 -maxdepth 1 -type d | sort); do
-    if [ -e "${__subdir}/.dircksum" ] && [ -n "${TRUST}" ]; then
-      [ -z "${SILENT}" ] && echo "INFO: Trusting/using existing checksum WITHOUT VERIFICATION (${__subdir})"
+  for __subdir in $(find "${DIRECTORY}/" -mindepth 1 -maxdepth 1 -type d | sort); do
+    if [ -z "${VERIFY}" ] && [ -e "${__subdir}/.dircksum" ]; then
+      [ -z "${SILENT}" ] && echo "INFO: Using existing checksum (${__subdir})"
       continue
     fi
     _dircksum "${__subdir}" $(( ${DEPTH}+1 ))
-    [ ${EXIT} -ne 0 ] && [ -z "${READONLY}" ] && return ${EXIT}
+    [ ${EXIT} -ne 0 ] && [ -z "${VERIFY}" ] && return ${EXIT}
   done
 
   # ... necessary to loose CPU cycles?
-  if [ -n "${READONLY}" ]; then
-    if [ ! -e "${DIRECTORY}/.dircksum" -o ! -r "${DIRECTORY}/.dircksum" ]; then
+  if [ -z "${CREATE}" ] && [ -n "${VERIFY}" ]; then
+    if [ ! -e "${DIRECTORY}/.dircksum" ] || [ ! -r "${DIRECTORY}/.dircksum" ]; then
       echo "WARNING: Missing/unreadable checksum file; can not verify checksum (${DIRECTORY})" >&2
       _exit 1; return ${EXIT}
     fi
   fi
 
   # ... extract checksum from sub-directories 'dircksum' file
-  __dircksum=$( ( find "${DIRECTORY}" -mindepth 1 -maxdepth 1 -type d | sort | sed 's/\/*$/\/.dircksum/' | xargs -d'\n' -r -n 1000 fgrep -h 'DIRCKSUM' ) | awk '{ if (NR==1) { CKSUM=$1; SIZE=$2; DIRS=$3+1; FILES=$4 } else { CKSUM=CKSUM":"$1; SIZE+=$2; DIRS+=$3+1; FILES+=$4 } }; END { if (NR>0) { printf "%s %.f %.f %.f\n",CKSUM,SIZE,DIRS,FILES } }'; exit ${PIPESTATUS[0]} ); __exit=$?
+  if [ "${VERSION}" == '1' ]; then
+    # V1: Sort the checksums according to the sub-directories names.
+    __dircksum=$( ( find "${DIRECTORY}/" -mindepth 1 -maxdepth 1 -type d | sort | sed 's/\/*$/\/.dircksum/' | xargs -d'\n' -r -n 1000 fgrep -h 'DIRCKSUM' 2>/dev/null ) | awk '{ if (NR==1) { CKSUM=$1; SIZE=$2; DIRS=$3+1; FILES=$4 } else { CKSUM=CKSUM":"$1; SIZE+=$2; DIRS+=$3+1; FILES+=$4 } }; END { if (NR>0) { printf "%s %.f %.f %.f\n",CKSUM,SIZE,DIRS,FILES } }'; exit ${PIPESTATUS[0]} ); __exit=$?
+  elif [ "${VERSION}" == '2' ]; then
+    # V2: Sort the checksums according to the cksum value instead of the sub-directories names.
+    #     This allows to rename sub-directories without changing the result of the checksum.
+    __dircksum=$( ( find "${DIRECTORY}/" -mindepth 1 -maxdepth 1 -type d | sed 's/\/*$/\/.dircksum/' | xargs -d'\n' -r -n 1000 fgrep -h 'DIRCKSUM' 2>/dev/null | sort -k1,1 -n ) | awk '{ if (NR==1) { CKSUM=$1; SIZE=$2; DIRS=$3+1; FILES=$4 } else { CKSUM=CKSUM":"$1; SIZE+=$2; DIRS+=$3+1; FILES+=$4 } }; END { if (NR>0) { printf "%s %.f %.f %.f\n",CKSUM,SIZE,DIRS,FILES } }'; exit ${PIPESTATUS[0]} ); __exit=$?
+  fi
   if [ ${__exit} -ne 0 ]; then
     echo "ERROR: An error occured while reading the sub-directories checksum (${__exit})" >&2
-    if [ -z "${READONLY}" ]; then
+    if [ -z "${VERIFY}" ]; then
       _exit 2; return ${EXIT}
     fi
   fi
@@ -116,10 +121,17 @@ function _dircksum {
   fi
 
   # ... compute checksum for files in current directory
-  __filecksum="$( ( find "${DIRECTORY}" -mindepth 1 -maxdepth 1 -type f -not -name '.dircksum' | sort | xargs -d'\n' -r -n 1000 cksum ) | sed 's|^\([^ ]*\) \([^ ]*\) \(.*\/\)\([^/]*\)$|\1 \2 \4|'; exit ${PIPESTATUS[0]} )"; __exit=$?
+  if [ "${VERSION}" == '1' ]; then
+    # V1: Sort the checksums according to the files names.
+    __filecksum="$( ( find "${DIRECTORY}/" -mindepth 1 -maxdepth 1 -type f -not -name '.dircksum' | sort | xargs -d'\n' -r -n 1000 cksum ) | sed 's|^\([^ ]*\) \([^ ]*\) \(.*\/\)\([^/]*\)$|\1 \2 \4|'; exit ${PIPESTATUS[0]} )"; __exit=$?
+  elif [ "${VERSION}" == '2' ]; then
+    # V2: Sort the checksums according to the cksum value instead of the files names.
+    #     This allows to rename files without changing the result of the checksum.
+    __filecksum="$( ( find "${DIRECTORY}/" -mindepth 1 -maxdepth 1 -type f -not -name '.dircksum' | xargs -d'\n' -r -n 1000 cksum | sort -k1,1 -n ) | sed 's|^\([^ ]*\) \([^ ]*\) \(.*\/\)\([^/]*\)$|\1 \2 \4|'; exit ${PIPESTATUS[0]} )"; __exit=$?
+  fi
   if [ ${__exit} -ne 0 ]; then
     echo "ERROR: An error occured while performing the files checksum (${__exit})" >&2
-    if [ -z "${READONLY}" ]; then
+    if [ -z "${VERIFY}" ]; then
       _exit 2; return ${EXIT}
     fi
   fi
@@ -131,33 +143,40 @@ function _dircksum {
     __files=$(( ${__files} + ${__dircksum%% *} ))
   fi
 
-  # ... check/save checksum
+  # ... save checksum
   __cksum=$(echo "${__cksum}" | cksum | cut -d' ' -f1)
-  if [ ! -e "${DIRECTORY}/.dircksum" ]; then
-    [ -z "${SILENT}" ] && echo "INFO: Checksum saved (${DIRECTORY})"
+  if [ ! -e "${DIRECTORY}/.dircksum" ] && [ -n "${CREATE}" ]; then
      cat << EOF > "${DIRECTORY}/.dircksum"
 # CKSUM[cksum] SIZE[bytes] DIRS[count] FILES[count] DATE[iso]
-${__cksum} ${__size} ${__dirs} ${__files} $(date +'%Y%m%dT%H%M%S') # DIRCKSUM
-# CKSUK[cksum] SIZE[bytes] FILE[name]
+${__cksum} ${__size} ${__dirs} ${__files} $(date +'%Y%m%dT%H%M%S') # DIRCKSUM (V:${VERSION})
+# CKSUM[cksum] SIZE[bytes] FILE[name]
 ${__filecksum}
 EOF
     [ $? -ne 0 ] && echo "ERROR: Failed to save checksum file (${DIRECTORY}/.dircksum)" >&2 && _exit 2 && return ${EXIT}
-    [ -n "${PRINT}" -a ${DEPTH} -eq 0 ] && cat "${DIRECTORY}/.dircksum"
-  elif [ ! -r "${DIRECTORY}/.dircksum" ]; then
+    [ -z "${SILENT}" ] && echo "INFO: Checksum saved (${DIRECTORY})"
+  fi
+  if [ -e "${DIRECTORY}/.dircksum" ] && [ ! -r "${DIRECTORY}/.dircksum" ]; then
     echo "WARNING: Unreadable checksum file (${DIRECTORY}/.dircksum)" >&2
     _exit 1; return ${EXIT}
-  else
+  fi
+
+  # ... print checksum
+  if [ -n "${PRINT}" -a ${DEPTH} -eq 0 ]; then
+    cat << EOF
+# CKSUM[cksum] SIZE[bytes] DIRS[count] FILES[count] DATE[iso]
+${__cksum} ${__size} ${__dirs} ${__files} $(date +'%Y%m%dT%H%M%S') # DIRCKSUM (V:${VERSION})
+# CKSUM[cksum] SIZE[bytes] FILE[name]
+${__filecksum}
+EOF
+  fi
+
+  # ... verify checksum
+  if [ -n "${VERIFY}" ]; then
     __dircksum=$(fgrep -h 'DIRCKSUM' "${DIRECTORY}/.dircksum")
     local __cksum_check=${__dircksum%% *}; __dircksum=${__dircksum#* }
     local __size_check=${__dircksum%% *}; __dircksum=${__dircksum#* }
     local __dirs_check=${__dircksum%% *}; __dircksum=${__dircksum#* }
     local __files_check=${__dircksum%% *}
-    [ -n "${PRINT}" -a ${DEPTH} -eq 0 ] && cat << EOF
-# CKSUM[cksum] SIZE[bytes] DIRS[count] FILES[count] DATE[iso]
-${__cksum} ${__size} ${__dirs} ${__files} $(date +'%Y%m%dT%H%M%S') # DIRCKSUM
-# CKSUK[cksum] SIZE[bytes] FILE[name]
-${__filecksum}
-EOF
     if [ "${__cksum_check}" != "${__cksum}" -o "${__size_check}" != "${__size}" -o "${__dirs_check}" != "${__dirs}" -o "${__files_check}" != "${__files}" ]; then
       #echo "DEBUG: ${__cksum} ${__size} ${__dirs} ${__files} <-> ${__cksum_check} ${__size_check} ${__dirs_check} ${__files_check}" >&2
       echo "ERROR: Checksum MISMATCH (${DIRECTORY})" >&2 && _exit 2; return ${EXIT}
@@ -174,13 +193,20 @@ EOF
 function _delete {
   # Arguments
   local DIRECTORY="${1}"
+  local DELETE="${2}"
+
+  # Crawl down
+  if [ "${DELETE}" == 'all' ]; then
+    find "${DIRECTORY}/" -mindepth 2 -name .dircksum -delete
+    [ $? -ne 0 ] && echo "ERROR: Failed to delete checksum files from sub-directories (${DIRECTORY}/.../.dircksum)" >&2 && _exit 2 && return ${EXIT}
+  fi
 
   # Delete checksum
   if [ -e "${DIRECTORY}/.dircksum" ]; then
+    rm -f "${DIRECTORY}/.dircksum"
+    [ $? -ne 0 ] && echo "ERROR: Failed to delete checksum file (${DIRECTORY}/.dircksum)" >&2 && _exit 2 && return ${EXIT}
     [ -z "${SILENT}" ] && echo "INFO: Checksum deleted (${DIRECTORY})"
-    rm "${DIRECTORY}/.dircksum"
   fi
-  [ -e "${DIRECTORY}/.dircksum" ] && echo 'ERROR: Failed to delete existing checksum (${DIRECTORY})' >&2 && _exit 2
 
   # Crawl up
   local DIRECTORY_NEW="$(dirname "${DIRECTORY}")"
@@ -190,48 +216,55 @@ function _delete {
 # Main
 while [ -n "${1}" ]; do
   case "${1}" in
-    '-v'|'--verbose')
+    '-V'|'--verbose')
       VERBOSE='yes'
       SILENT=
       ;;
-    '-s'|'--silent')
+    '-S'|'--silent')
       SILENT='yes'
       VERBOSE=
       ;;
-    '-t'|'--trust')
-      TRUST='yes'
-      READONLY=
+    '-c'|'--create')
+      CREATE='yes'
       DELETE=
       ;;
-    '-r'|'--read-only')
-      READONLY='yes'
-      TRUST=
+    '-v'|'--verify')
+      VERIFY='yes'
       DELETE=
-      ;;
-    '-p'|'--print')
-      PRINT='yes'
       ;;
     '-d'|'--delete')
       DELETE='yes'
-      TRUST=
-      READONLY=
+      CREATE=
+      VERIFY=
+      ;;
+    '-dd'|'--delete-all')
+      DELETE='all'
+      CREATE=
+      VERIFY=
+      ;;
+    '-p'|'--print')
+      PRINT='yes'
+      SILENT='yes'
+      ;;
+    '-1')
+      VERSION='1'
       ;;
     *)
       if [ "${1:0:1}" == '-' ]; then
         echo "WARNING: Invalid option (${1})" >&2
       else
         DIRECTORY="${1%%/}"
-        [ -z "${DIRECTORY}" ] && echo 'ERROR: Please specify a directory' >&2 && exit 2
-        [ ! -d "${DIRECTORY}" ] && echo "ERROR: Missing/invalid directory (${DIRECTORY})" >&2 && exit 2
+        [ -z "${DIRECTORY}" ] && echo 'WARNING: Please specify a directory' >&2 && shift && continue
+        [ ! -d "${DIRECTORY}" ] && echo "WARNING: Missing/invalid directory (${DIRECTORY})" >&2 && shift && continue
         if [ -n "${DELETE}" ]; then
           pushd "${DIRECTORY}" >/dev/null
           DIRECTORY="$(pwd)"
           popd >/dev/null
-          _delete "${DIRECTORY}"
+          _delete "${DIRECTORY}" ${DELETE}
         else
           _dircksum "${DIRECTORY}" 0
         fi
-        [ ${EXIT} -ne 0 ] && [ -z "${READONLY}" -a -z "${DELETE}" ] && exit ${EXIT}
+        [ ${EXIT} -ne 0 ] && [ -z "${VERIFY}" -a -z "${DELETE}" ] && exit ${EXIT}
       fi
       ;;
   esac
