- [kvm-helper] Added launch confirmation prompt

diff --git a/system/kvm-helper b/system/kvm-helper
--- a/system/kvm-helper
+++ b/system/kvm-helper
@@ -224,5 +224,7 @@ MY_KVM="${MY_KVM} ${MY_OPTIONS}"
 # KVM start
 [ -z "$(lsmod | fgrep kvm)" ] && echo "ERROR: KVM kernel modules are not loaded" >&2 &&  exit 1
 echo "${MY_KVM}" >&2
+echo 'PRESS <ENTER> TO CONTINUE, <CTRL+C> To ABORT...' >&2
+read
 eval "${MY_KVM}"
 
