[qemu-easy] Allow to setup network interface by MAC address (+mac ...)

diff --git a/system/qemu-easy b/system/qemu-easy
--- a/system/qemu-easy
+++ b/system/qemu-easy
@@ -22,7 +22,7 @@ SYNOPSIS:
   Network settings - when applicable - are automatically adjusted to match
   the given hostname, according to the corresponding IPv4 address and the
   '~/.qemu/network.cfg' file, formatted as:
-    <ip-regexp>:<tap-if>[,<tap-if>,...]
+    <ip/mac-regexp>=<tap-if>[,<tap-if>,...]
 
 COMMAND: info
   ${0##*/} info <hostname|ip-address>
@@ -46,8 +46,12 @@ COMMAND: start
       Add secondary CD/DVD drive with corresponding ISO image
 
     +net <hostname|ip-address>
-      Add network interface for corresponding host name
-      (which MUST match a valid IP address and network; see ~/.qemu/network.cfg)
+      Add network interface for corresponding IP address or host name
+      (which MUST match a network interface; see ~/.qemu/network.cfg)
+
+    +mac <mac-address>
+      Add network interface for corresponding MAC address
+      (which MUST match a network interface; see ~/.qemu/network.cfg)
 
     +boot {hd|cd|net}
       Boot device
@@ -120,6 +124,7 @@ MY_HD2=
 MY_CD1=
 MY_CD2=
 MY_NET=
+MY_MAC=
 MY_BOOT=
 MY_UEFI=
 MY_DEV_BLK=
@@ -163,6 +168,12 @@ while [ -n "${1}" ]; do
       [ -z "${2}" ] && echo "ERROR: Missing option parameter (${1})" >&2 && exit 1
       shift
       MY_NET="${1}"
+      ;;
+
+    '+mac')
+      [ -z "${2}" ] && echo "ERROR: Missing option parameter (${1})" >&2 && exit 1
+      shift
+      MY_MAC="${1}"
       ;;
 
     '+boot')
@@ -246,7 +257,7 @@ while [ -n "${1}" ]; do
         MY_COMMAND="${1}"
       else
         case "${MY_COMMAND}" in
-          'info') MY_NET="${1}";;
+          'netinfo') MY_NET="${1}";;
           'vnc') MY_VNC="${1}";;
           'stop'|'shutdown'|'reset'|'kill'|'destroy'|'suspend'|'pause'|'resume'|'continue'|'cont') MY_HD1="${1}";;
           'console'|'monitor') MY_HD1="${1}"; shift; break;;
@@ -292,10 +303,9 @@ esac
 # ... network
 MY_FQHN=
 MY_IPV4=
-MY_MAC=
 MY_IFACES=
-MY_UUID="51454D55-4845-4C50-4552-$(echo "${MY_HD1}" | md5sum | sed 's/^\(............\).*$/\1/')"  # QEMU-HE-LP-ER-...
 if [ -n "${MY_NET}" ]; then
+
   # IP address and FQHN
   if [ -n "$(echo "${MY_NET}" | egrep '^[0-9]{2,3}(\.[0-9]{1,3}){3}$')" ]; then
     MY_IPV4="${MY_NET}"
@@ -317,24 +327,37 @@ if [ -n "${MY_NET}" ]; then
   [ -z "$(echo "${MY_MAC}" | egrep '^[A-F0-9]{2}(:[A-F0-9]{2}){5}$')" ] && echo "ERROR: Invalid MAC address (${MY_MAC})" >&2 && exit 1
 
   # Network interface
-  if [ -r ~/.qemu/network.cfg ]; then
-    for regexp_ifaces in $(sed 's/#.*//g;s/  *$//' ~/.qemu/network.cfg | grep -v '^$'); do
-      regexp=${regexp_ifaces%%:*}; ifaces=${regexp_ifaces##*:}
-      [ -n "$(echo ${MY_IPV4} | grep "^${regexp//./\\.}")" ] && MY_IFACES=${ifaces} && break
-    done
-  else
-    echo "WARNING: Missing/unreadable network configuration file (~/.qemu/network.cfg)" >&2
-  fi
+  [ ! -r ~/.qemu/network.cfg ] && echo "ERROR: Missing/unreadable network configuration file (~/.qemu/network.cfg)" >&2 && exit 1
+  for regexp_ifaces in $(sed 's/#.*//g;s/ //g' ~/.qemu/network.cfg | grep -v '^$'); do
+    regexp=${regexp_ifaces%%=*}; ifaces=${regexp_ifaces##*=}
+    [ -n "$(echo ${MY_IPV4} | grep -i "^${regexp//./\\.}")" ] && MY_IFACES=${ifaces} && break
+  done
+  [ -z "${MY_IFACES}" ] && echo "ERROR: No network/interfaces matches the given IP address (${MY_IPV4})" >&2 && exit 1
 
-  # UUID
-  MY_UUID="${MY_UUID:0:24}${MY_MAC//:/}"
+elif [ -n "${MY_MAC}" ]; then
+
+  # MAC address
+  [ -z "$(echo "${MY_MAC}" | egrep -i '^[A-F0-9]{2}(:[A-F0-9]{2}){5}$')" ] && echo "ERROR: Invalid MAC address (${MY_MAC})" >&2 && exit 1
+
+  # Network interface
+  [ ! -r ~/.qemu/network.cfg ] && echo "ERROR: Missing/unreadable network configuration file (~/.qemu/network.cfg)" >&2 && exit 1
+  for regexp_ifaces in $(sed 's/#.*//g;s/ //g' ~/.qemu/network.cfg | grep -v '^$'); do
+    regexp=${regexp_ifaces%%=*}; ifaces=${regexp_ifaces##*=}
+    [ -n "$(echo ${MY_MAC} | grep -i "^${regexp//./\\.}")" ] && MY_IFACES=${ifaces} && break
+  done
+  [ -z "${MY_IFACES}" ] && echo "ERROR: No network/interfaces matches the given MAC address (${MY_MAC})" >&2 && exit 1
+
 fi
+
+# ... UUID
+MY_UUID="51454D55-4845-4C50-4552-$(echo "${MY_HD1}" | md5sum | sed 's/^\(............\).*$/\1/')"  # QEMU-HE-LP-ER-...
+[ -n "${MY_MAC}" ] && MY_UUID="${MY_UUID:0:24}${MY_MAC//:/}"
 
 
 ## Command
 case "${MY_COMMAND}" in
 
-  'info')
+  'netinfo')
     [ -z "${MY_NET}" ] && echo 'ERROR: Missing argument (<hostname>)' >&2 && exit 1
     cat << EOF
 HOST INFORMATION:
@@ -358,7 +381,7 @@ EOF
 
     # ... console
     if [ "${MY_STDIO}" == 'console' ]; then
-      QEMU_CMD="${QEMU_CMD}|-serial stdio"
+      QEMU_CMD="${QEMU_CMD}|-serial mon:stdio"
     else
       QEMU_CMD="${QEMU_CMD}|-serial unix:'${MY_PATH_CONSOLE}',server,nowait"
     fi
@@ -402,8 +425,7 @@ EOF
     fi
 
     # ... network
-    if [ -n "${MY_NET}" ]; then
-      [ -z "${MY_IFACES}" ] && echo "ERROR: No network/interfaces match the given hostname/IP address (${MY_IPV4})" >&2 && exit 1
+    if [ -n "${MY_MAC}" ]; then
       MY_IFACE=
       for iface in $(echo ${MY_IFACES} | tr ',' '\n'); do
         [ -z "$(pgrep -f "ifname=${iface}")" ] && MY_IFACE=${iface} && break
