[tomato-backup] FIX: Allow 'tomato-backup' to be used in batch mode via                 remote SSH connections.

diff --git a/system/tomato-backup b/system/tomato-backup
--- a/system/tomato-backup
+++ b/system/tomato-backup
@@ -27,6 +27,10 @@ OPTIONS:
   --gpg-decrypt
     Decrypt the specified 'wgetrc' configuration file using GnuPG.
     Decryption password will be prompted via stderr/stdin.
+
+  --gpg-passphrase-fd <fd>
+    Switch GPG decryption to batch mode and get the passphrase
+    from the specified file descriptor.
 EOF
 
 # Arguments
@@ -36,6 +40,7 @@ BACKUP_SSH=
 PATH_WGETRC=
 PATH_OUTPUT='-'
 GPG_DECRYPT=
+GPG_PASS_FD=
 while [ -n "${1}" ]; do
   case "${1}" in
     -W|--web)
@@ -57,6 +62,11 @@ while [ -n "${1}" ]; do
     --gpg-decrypt)
       GPG_DECRYPT='yes'
       ;;
+    --gpg-passphrase-fd)
+      shift
+      [ -z "${1}" ] && echo "ERROR: Missing/empty file descriptor for GPG passphrase" >&2 && exit 1
+      GPG_PASS_FD="${1}"
+      ;;
     -*)
       echo "ERROR: Invalid option (${1})" >&2 && exit 1
       ;;
@@ -74,7 +84,7 @@ done
 # SSH (nvram) backup
 if [ -n "${BACKUP_SSH}" ]; then
   [ "${PATH_OUTPUT}" != '-' ] && exec 3>&1 1>"${PATH_OUTPUT}"
-  ssh -t -l root ${DEVICE} 'nvram export --set' | grep '^nvram set'
+  ssh -o ForwardX11=no -l root ${DEVICE} 'nvram export --set'
   [ "${PATH_OUTPUT}" != '-' ] && exec 1>&3
 fi
 
@@ -88,7 +98,11 @@ if [ -n "${BACKUP_WEB}" ]; then
   touch ~/.wgetrc || exit 1
   chmod go= ~/.wgetrc || exit 1
   if [ -n "${GPG_DECRYPT}" ]; then
-    gpg --decrypt "${PATH_WGETRC}" > ~/.wgetrc || exit 1
+    if [ -n "${GPG_PASS_FD}" ]; then
+      gpg --batch --passphrase-fd ${GPG_PASS_FD} --decrypt "${PATH_WGETRC}" > ~/.wgetrc || exit 1
+    else
+      gpg --decrypt "${PATH_WGETRC}" > ~/.wgetrc || exit 1
+    fi
   else
     cat "${PATH_WGETRC}" > ~/.wgetrc || exit 1
   fi
