[{lame,imagick}-downsample] allow to target a single file

diff --git a/multimedia/imagick-downsample b/multimedia/imagick-downsample
--- a/multimedia/imagick-downsample
+++ b/multimedia/imagick-downsample
@@ -1,8 +1,10 @@
 #!/bin/bash
+SCRIPT="${0##*/}"
 
-# Command-line
-[ $# -lt 2 -o "${1##*-}" == 'help' ] && cat << EOF && exit 1
-USAGE: ${0##*/} [<option> ...] <source-dir> <destination-dir>
+## Usage
+__USAGE() {
+  cat >&2 <<EOF
+USAGE: ${SCRIPT} [<option> ...] <source-dir/file> <destination-dir/file>
 
 SYNOPSIS:
   Downsample or transcode (to JPEG format) all image files found in the source
@@ -18,20 +20,33 @@ OPTIONS:
 AUTHOR:
   Cedric Dufour - http://cedric.dufour.name
 EOF
+}
+[ $# -lt 2 ] && __USAGE && exit 1
 
 # Arguments
 SIZE_GAUGE=1024
 JPEG_QUALITY=80
+__OPTION() {
+  [ -z "${2}" ] && echo "ERROR[${SCRIPT}]: Missing option parameter (${1})" >&2 && exit 1
+  return 0
+}
 while [ -n "${1}" ]; do
   case "${1}" in
-    '-g'|'--gauge')  
-      shift; [ -z "${1}" ] && echo 'ERROR: Missing option value (--gauge)' >&2 && exit 1; SIZE_GAUGE="${1}";;
+    '-h'|'--help'|'help')
+      __USAGE; exit 1;;
+    '-g'|'--gauge')
+      __OPTION "${@}"; SIZE_GAUGE="${2}"; shift;;
     '-q'|'--quality')
-      shift; [ -z "${1}" ] && echo 'ERROR: Missing option value (--quality)' >&2 && exit 1; JPEG_QUALITY="${1}";;
+      __OPTION "${@}"; JPEG_QUALITY="${2}"; shift;;
+    -*)
+        echo "ERROR[${SCRIPT}]: Invalid option (${1})" >&2; exit 1;;
     *)
-      if [ -z "${SRC_DIR}" ]; then SRC_DIR="${1}"
-      elif [ -z "${DST_DIR}" ]; then DST_DIR="${1}"
-      else echo 'ERROR: Invalid (extra) argument' >&2 && exit 1
+      if [ -z "${SRC}" ]; then
+        SRC="${1}"
+      elif [ -z "${DST}" ]; then
+        DST="${1}"
+      else
+        echo "ERROR[${SCRIPT}]: Invalid argument (${1})" >&2; exit 1
       fi
       ;;
   esac
@@ -42,68 +57,95 @@ done
 [ -z "$(which convert)" ] && echo "ERROR[$$]: 'convert' cannot be found" >&2 && exit 1
 
 # Check directories and files
-SRC_DIR=${SRC_DIR%%/}
-DST_DIR=${DST_DIR%%/}
-[ ! -d "${SRC_DIR}" ] && echo "ERROR[$$]: Invalid source directory (${SRC_DIR})" >&2 && exit 1
-[ ! -r "${SRC_DIR}" ] && echo "ERROR[$$]: Unable to read from source directory (${SRC_DIR})" >&2 && exit 1
-[ ! -d "${DST_DIR}" ] && echo "ERROR[$$]: Invalid destination directory (${DST_DIR})" >&2 && exit 1
-[ ! -w "${DST_DIR}" ] && echo "ERROR[$$]: Unable to write to destination directory (${DST_DIR})" >&2 && exit 1
+if [ ! -f "${SRC}" ]; then
+  SRC=${SRC%%/}
+  DST=${DST%%/}
+  [ ! -d "${SRC}" ] && echo "ERROR[${SCRIPT}($$)]: Invalid source directory (${SRC})" >&2 && exit 1
+  [ ! -r "${SRC}" ] && echo "ERROR[${SCRIPT}($$)]: Unable to read from source directory (${SRC})" >&2 && exit 1
+  [ ! -d "${DST}" ] && echo "ERROR[${SCRIPT}($$)]: Invalid destination directory (${DST})" >&2 && exit 1
+  [ ! -w "${DST}" ] && echo "ERROR[${SCRIPT}($$)]: Unable to write to destination directory (${DST})" >&2 && exit 1
+fi
 
-# Lock function
-DST_LOCK="${DST_DIR}/.lock"
-function atomic_begin {
+
+## Helper functions
+
+# Lock
+DST_LOCK="${DST}/.lock"
+__atomic_begin() {
   n=100; while true; do # loop for ~5 seconds (100 x 0.05 seconds in average)
-    n=$(( ${n}-1 ))
-    [ ${n} -le 0 ] && echo "ERROR[$$]: Failed to acquire lock (${DST_LOCK})" >&2 && exit 1
-    [ $(( ${n} % 10 )) -eq 0 ] && echo "WARNING[$$]: Waiting for lock (${DST_LOCK})" >&2
+    n=$(( n-1 ))
+    [ ${n} -le 0 ] && echo "ERROR[${SCRIPT}($$)]: Failed to acquire lock (${DST_LOCK})" >&2 && exit 1
+    [ $(( n % 10 )) -eq 0 ] && echo "WARNING[${SCRIPT}($$)]: Waiting for lock (${DST_LOCK})" >&2
     if ( set -o noclobber; echo -n > "${DST_LOCK}" ) 2>/dev/null; then
       break
     fi
-    sleep 0.0$(( ${RANDOM} % 10 ))
+    sleep 0.0$(( RANDOM % 10 ))
   done
 }
-function atomic_end {
+__atomic_end() {
   rm -f "${DST_LOCK}"
 }
 
-# Trap signals
-trap 'echo "INTERRUPT[$$]: Cleaning and aborting" >&2; rm -f "${DST_LOCK}" "${p_dst}"; exit 2' INT TERM
-
-# Loop through image files
-echo "INFO[$$]: Looking for files to transcode..."
-IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.tif' -o -iname '*.tiff'  \)" | sort); do
-  # Compute source parameters
-  d_src="$(dirname ${p_src})"
-  [ -e "${d_src}/.nodownsample" ] && continue
-  e_src="${p_src##*.}"
-
-  # Compute destination parameters
-  p_dst="${p_src%.*}.jpg"
-  p_dst="${DST_DIR}/${p_dst#${SRC_DIR}/}"
-  d_dst="$(dirname ${p_dst})"
-  f_dst="$(basename ${p_dst})"
-
-  # Check/create destination directory
-  [ ! -d "${d_dst}" ] && mkdir -p "${d_dst}"
-  [ ! -d "${d_dst}" ] && echo "WARNING[$$]: Failed to create destination directory (${d_dst}); skipping..." >&2 && continue
-  [ ! -w "${d_dst}" ] && echo "WARNING[$$]: Unable to write to destination directory (${d_dst}): skipping..." >&2 && continue
-
-  # Check destination file
-  atomic_begin
-  [ -e "${p_dst}" ] && atomic_end && continue
-  touch "${p_dst}"
-  atomic_end
+# Transcode
+__transcode() {
+  p_src="${1}"
+  p_dst="${2}"
 
   # Transcoding
-  echo "INFO[$$]: Transcoding ${p_src} -> ${p_dst}"
+  echo "INFO[${SCRIPT}($$)]: Transcoding ${p_src} -> ${p_dst}"
 
   # Downsample/transcode image file
   eval "convert \"${p_src}\" -resize '${SIZE_GAUGE}x${SIZE_GAUGE}>' -quality ${JPEG_QUALITY} +profile '*' \"${p_dst}\""
-  [ $? -ne 0 ] && echo "WARNING[$$]: An error occured while transcoding (${p_aux} -> ${p_dst}); skipping..." >&2 && continue
-   
-done
+}
+
+
+## Main
+
+# Trap signals
+trap 'echo "INTERRUPT[${SCRIPT}($$)]: Cleaning and aborting" >&2; rm -f "${DST_LOCK}" "${p_dst}"; exit 2' INT TERM
+
+# Loop through image files
+if [ -f "${SRC}" ]; then
+  p_src="${SRC}"
+  p_dst="${DST%.*}.jpg"
+
+  # Transcoding
+  if ! __transcode "${p_src}" "${p_dst}"; then
+    echo "ERROR[${SCRIPT}($$)]: An error occured while transcoding (${p_src} -> ${p_dst}); skipping..." >&2
+    exit 1
+  fi
+else
+  echo "INFO[${SCRIPT}($$)]: Looking for files to transcode..."
+  IFS=$'\n'
+  for p_src in $(eval "find '${SRC}' \( -type f -o -type l \) \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.tif' -o -iname '*.tiff'  \)" | sort); do
+    # Compute source parameters
+    d_src="$(dirname "${p_src}")"
+    [ -e "${d_src}/.nodownsample" ] && continue
+
+    # Compute destination parameters
+    p_dst="${p_src%.*}.jpg"
+    p_dst="${DST}/${p_dst#${SRC}/}"
+    d_dst="$(dirname "${p_dst}")"
+
+    # Check/create destination directory
+    [ ! -d "${d_dst}" ] && mkdir -p "${d_dst}"
+    [ ! -d "${d_dst}" ] && echo "WARNING[${SCRIPT}($$)]: Failed to create destination directory (${d_dst}); skipping..." >&2 && continue
+    [ ! -w "${d_dst}" ] && echo "WARNING[${SCRIPT}($$)]: Unable to write to destination directory (${d_dst}): skipping..." >&2 && continue
+
+    # Check destination file
+    __atomic_begin
+    [ -e "${p_dst}" ] && __atomic_end && continue
+    touch "${p_dst}"
+    __atomic_end
+
+    # Transcoding
+    if ! __transcode "${p_src}" "${p_dst}"; then
+      echo "WARNING[${SCRIPT}($$)]: An error occured while transcoding (${p_src} -> ${p_dst}); skipping..." >&2
+      continue
+    fi
+  done
+fi
 
 # Done
-echo "INFO[$$]: Done"
+echo "INFO[${SCRIPT}($$)]: Done"
 exit 0
-
diff --git a/multimedia/lame-downsample b/multimedia/lame-downsample
--- a/multimedia/lame-downsample
+++ b/multimedia/lame-downsample
@@ -1,8 +1,10 @@
 #!/bin/bash
+SCRIPT="${0##*/}"
 
-# Command-line
-[ $# -lt 2 -o "${1##*-}" == 'help' ] && cat << EOF && exit 1
-USAGE: ${0##*/} [<option> ...] <source-dir> <destination-dir>
+## Usage
+__USAGE() {
+  cat >&2 <<EOF
+USAGE: ${SCRIPT} [<option> ...] <source-dir/file> <destination-dir/file>
 
 SYNOPSIS:
   Downsample or transcode (to MP3 format) all audio files found in the source
@@ -23,23 +25,36 @@ OPTIONS:
 AUTHOR:
   Cedric Dufour - http://cedric.dufour.name
 EOF
+}
+[ $# -lt 2 ] && __USAGE && exit 1
 
 # Arguments
 TARGET_KBS=128
 LAME_OPTS='--preset standard'
 LAME_COMMENT='#AUTO#'
+__OPTION() {
+  [ -z "${2}" ] && echo "ERROR[${SCRIPT}]: Missing option parameter (${1})" >&2 && exit 1
+  return 0
+}
 while [ -n "${1}" ]; do
   case "${1}" in
+    '-h'|'--help'|'help')
+      __USAGE; exit 1;;
     '-b'|'--bitrate')  
-      shift; [ -z "${1}" ] && echo 'ERROR: Missing option value (--bitrate)' >&2 && exit 1; TARGET_KBS="${1}";;
+      __OPTION "${@}"; TARGET_KBS="${2}"; shift;;
     '-l'|'--lameopts')
-      shift; [ -z "${1}" ] && echo 'ERROR: Missing option value (--lameopts)' >&2 && exit 1; LAME_OPTS="${1}";;
+      __OPTION "${@}"; LAME_OPTS="${2}"; shift;;
     '-c'|'--comment')
-      shift; [ -z "${1}" ] && echo 'ERROR: Missing option value (--comment)' >&2 && exit 1; LAME_COMMENT="${1}";;
+      __OPTION "${@}"; LAME_COMMENT="${2}"; shift;;
+    -*)
+        echo "ERROR[${SCRIPT}]: Invalid option (${1})" >&2; exit 1;;
     *)
-      if [ -z "${SRC_DIR}" ]; then SRC_DIR="${1}"
-      elif [ -z "${DST_DIR}" ]; then DST_DIR="${1}"
-      else echo 'ERROR: Invalid (extra) argument' >&2 && exit 1
+      if [ -z "${SRC}" ]; then
+        SRC="${1}"
+      elif [ -z "${DST}" ]; then
+        DST="${1}"
+      else
+        echo "ERROR[${SCRIPT}]: Invalid argument (${1})" >&2; exit 1
       fi
       ;;
   esac
@@ -47,78 +62,59 @@ while [ -n "${1}" ]; do
 done
 
 # Check dependencies (and format support)
-[ -z "$(which lame)" ] && echo "ERROR[$$]: 'lame' cannot be found" >&2 && exit 1
-AAC_INCL='yes'; [ -z "$(which faad)" ] && echo "WARNING[$$]: 'faad' cannot be found; '*.m4a' files will not be transcoded" >&2 && AAC_INCL=
-FLAC_INCL='yes'; [ -z "$(which flac)" ] && echo "WARNING[$$]: 'flac' cannot be found; '*.flac' files will not be transcoded" >&2 && FLAC_INCL=
-ID3_INCL='yes'; [ -z "$(which id3info)" ] && echo "WARNING[$$]: 'id3info' cannot be found; tags will not be retrieved from '*.mp3' files" >&2 && ID3_INCL=
-METAFLAC_INCL='yes'; [ -z "$(which metaflac)" ] && echo "WARNING[$$]: 'metaflac' cannot be found; tags will not be retrieved from '*.flac' files" >&2 && METAFLAC_INCL=
+[ -z "$(which lame)" ] && echo "ERROR[${SCRIPT}($$)]: 'lame' cannot be found" >&2 && exit 1
+AAC_INCL='yes'; [ -z "$(which faad)" ] && echo "WARNING[${SCRIPT}($$)]: 'faad' cannot be found; '*.m4a' files will not be transcoded" >&2 && AAC_INCL=
+FLAC_INCL='yes'; [ -z "$(which flac)" ] && echo "WARNING[${SCRIPT}($$)]: 'flac' cannot be found; '*.flac' files will not be transcoded" >&2 && FLAC_INCL=
+ID3_INCL='yes'; [ -z "$(which id3info)" ] && echo "WARNING[${SCRIPT}($$)]: 'id3info' cannot be found; tags will not be retrieved from '*.mp3' files" >&2 && ID3_INCL=
+METAFLAC_INCL='yes'; [ -z "$(which metaflac)" ] && echo "WARNING[${SCRIPT}($$)]: 'metaflac' cannot be found; tags will not be retrieved from '*.flac' files" >&2 && METAFLAC_INCL=
 
 # Check directories and files
-SRC_DIR=${SRC_DIR%%/}
-DST_DIR=${DST_DIR%%/}
-[ ! -d "${SRC_DIR}" ] && echo "ERROR[$$]: Invalid source directory (${SRC_DIR})" >&2 && exit 1
-[ ! -r "${SRC_DIR}" ] && echo "ERROR[$$]: Unable to read from source directory (${SRC_DIR})" >&2 && exit 1
-[ ! -d "${DST_DIR}" ] && echo "ERROR[$$]: Invalid destination directory (${DST_DIR})" >&2 && exit 1
-[ ! -w "${DST_DIR}" ] && echo "ERROR[$$]: Unable to write to destination directory (${DST_DIR})" >&2 && exit 1
+if [ ! -f "${SRC}" ]; then
+  SRC=${SRC%%/}
+  DST=${DST%%/}
+  [ ! -d "${SRC}" ] && echo "ERROR[${SCRIPT}($$)]: Invalid source directory (${SRC})" >&2 && exit 1
+  [ ! -r "${SRC}" ] && echo "ERROR[${SCRIPT}($$)]: Unable to read from source directory (${SRC})" >&2 && exit 1
+  [ ! -d "${DST}" ] && echo "ERROR[${SCRIPT}($$)]: Invalid destination directory (${DST})" >&2 && exit 1
+  [ ! -w "${DST}" ] && echo "ERROR[${SCRIPT}($$)]: Unable to write to destination directory (${DST})" >&2 && exit 1
+fi
 
-# Lock function
-DST_LOCK="${DST_DIR}/.lock"
-function atomic_begin {
+
+## Helper functions
+
+# Lock
+DST_LOCK="${DST}/.lock"
+__atomic_begin() {
   n=100; while true; do # loop for ~5 seconds (100 x 0.05 seconds in average)
-    n=$(( ${n}-1 ))
-    [ ${n} -le 0 ] && echo "ERROR[$$]: Failed to acquire lock (${DST_LOCK})" >&2 && exit 1
-    [ $(( ${n} % 10 )) -eq 0 ] && echo "WARNING[$$]: Waiting for lock (${DST_LOCK})" >&2
+    n=$(( n-1 ))
+    [ ${n} -le 0 ] && echo "ERROR[${SCRIPT}($$)]: Failed to acquire lock (${DST_LOCK})" >&2 && exit 1
+    [ $(( n % 10 )) -eq 0 ] && echo "WARNING[${SCRIPT}($$)]: Waiting for lock (${DST_LOCK})" >&2
     if ( set -o noclobber; echo -n > "${DST_LOCK}" ) 2>/dev/null; then
       break
     fi
-    sleep 0.0$(( ${RANDOM} % 10 ))
+    sleep 0.0$(( RANDOM % 10 ))
   done
 }
-function atomic_end {
+__atomic_end() {
   rm -f "${DST_LOCK}"
 }
 
-# Check/create ID3 comment
-[ "${LAME_COMMENT}" == "#AUTO#" ] && LAME_COMMENT="Transcoded with ${0##*/} (${LAME_OPTS})"
-
-# Trap signals
-trap 'echo "INTERRUPT[$$]: Cleaning and aborting" >&2; rm -f "${DST_LOCK}" "${p_dst}"; exit 2' INT TERM
-
-# Loop through audio files
-echo "INFO[$$]: Looking for files to transcode..."
-IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -iname '*.wav' -o -iname '*.mp3' ${AAC_INCL:+-o -iname '*.aac' -o -iname '*.m4a' -o -iname '*.mp4'} ${FLAC_INCL:+-o -iname '*.flac'} \)" | sort); do
-  # Compute source parameters
-  d_src="$(dirname ${p_src})"
-  [ -e "${d_src}/.nodownsample" ] && continue
-  e_src="${p_src##*.}"
-
-  # Compute destination parameters
-  p_dst="${p_src%.*}.mp3"
-  p_dst="${DST_DIR}/${p_dst#${SRC_DIR}/}"
-  d_dst="$(dirname ${p_dst})"
-  f_dst="$(basename ${p_dst})"
-
-  # Check/create destination directory
-  [ ! -d "${d_dst}" ] && mkdir -p "${d_dst}"
-  [ ! -d "${d_dst}" ] && echo "WARNING[$$]: Failed to create destination directory (${d_dst}); skipping..." >&2 && continue
-  [ ! -w "${d_dst}" ] && echo "WARNING[$$]: Unable to write to destination directory (${d_dst}): skipping..." >&2 && continue
-
-  # Check destination file
-  atomic_begin
-  [ -e "${p_dst}" ] && atomic_end && continue
-  touch "${p_dst}"
-  atomic_end
+# Transcoding
+__transcode() {
+  p_src="${1}"
+  p_dst="${2}"
 
   # Transcoding
-  echo "INFO[$$]: Transcoding ${p_src} -> ${p_dst}"
+  echo "INFO[${SCRIPT}($$)]: Transcoding ${p_src} -> ${p_dst}"
 
   # Extract tags from file
   tt=; tl=; ta=; tn=; ty=; br=
+  e_src="${p_src##*.}"
   case "${e_src}" in
 
     'mp3')
       if [ -n "${ID3_INCL}" ]; then
-        IFS=$'\n'; for tag in $(id3info "${p_src}" | egrep -i '(TIT2|TALB|TPE1|TRCK|TYER|Bitrate)' | awk -F ': ' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TIT2\|TALB\|TPE1\|TRCK\|TYER\|Bitrate\).*|/\1|/i' | iconv -f latin1 -t utf8 ); do
+        IFS=$'\n'
+        for tag in $(id3info "${p_src}" | grep -Fi '(TIT2|TALB|TPE1|TRCK|TYER|Bitrate)' | awk -F ': ' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TIT2\|TALB\|TPE1\|TRCK\|TYER\|Bitrate\).*|/\1|/i' | iconv -f latin1 -t utf8 ); do
           key="${tag%%|*}"
           case "${key^^}" in
             'TIT2') tt="${tag##*|}";;
@@ -126,14 +122,15 @@ IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -i
             'TPE1') ta="${tag##*|}";;
             'TRCK') tn="${tag##*|}";;
             'TYER') ty="${tag##*|}";;
-            'BITRATE') br="$(echo ${tag##*|} | sed 's/[^0-9]//g')";;
+            'BITRATE') br="$(echo "${tag##*|}" | sed 's/[^0-9]//g')";;
           esac
         done
       fi
       ;;
 
     'aac'|'m4a'|'mp4')
-      IFS=$'\n'; for tag in $(faad --info "${p_src}" 2>&1 | egrep -i '^(TITLE|ALBUM|ARTIST|TRACK|DATE):' | awk -F ': ' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TITLE\|ALBUM\|ARTIST\|TRACK\|DATE\).*|/\1|/i' ); do
+      IFS=$'\n'
+      for tag in $(faad --info "${p_src}" 2>&1 | grep -Fi '^(TITLE|ALBUM|ARTIST|TRACK|DATE):' | awk -F ': ' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TITLE\|ALBUM\|ARTIST\|TRACK\|DATE\).*|/\1|/i' ); do
         key="${tag%%|*}"
         case "${key^^}" in
           'TITLE') tt="${tag##*|}";;
@@ -147,7 +144,8 @@ IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -i
 
     'flac')
       if [ -n "${METAFLAC_INCL}" ]; then
-        IFS=$'\n'; for tag in $(metaflac --export-tags-to=- "${p_src}" | egrep -i '^(TITLE|ALBUM|ARTIST|TRACKNUMBER|DATE)=' | awk -F '=' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TITLE\|ALBUM\|ARTIST\|TRACKNUMBER\|DATE\).*|/\1|/i' ); do
+        IFS=$'\n'
+        for tag in $(metaflac --export-tags-to=- "${p_src}" | grep -Fi '^(TITLE|ALBUM|ARTIST|TRACKNUMBER|DATE)=' | awk -F '=' 'BEGIN {OFS="|"} {print $1,$2}' | sed 's/.*\(TITLE\|ALBUM\|ARTIST\|TRACKNUMBER\|DATE\).*|/\1|/i' ); do
           key="${tag%%|*}"
           case "${key^^}" in
             'TITLE') tt="${tag##*|}";;
@@ -169,9 +167,9 @@ IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -i
   [ -n "${ty}" ] && tags="${tags} --ty \"${ty}\""
   [ -n "${LAME_COMMENT}" ] && tags="${tags} --tc \"${LAME_COMMENT}\" "
   [ -n "${tags}" ] && tags="--add-id3v2 --id3v2-latin1 ${tags}"
-   
+
   # Downsample/transcode audio file
-  if [ "${e_src}" == 'mp3' -a -n "${br}" ] && [ ${br} -le ${TARGET_KBS} ]; then
+  if [ "${e_src}" == 'mp3' ] && [ -n "${br}" ] && [ "${br}" -le "${TARGET_KBS}" ]; then
     eval "cp \"${p_src}\" \"${p_dst}\""
   else
     case "${e_src}" in
@@ -190,11 +188,58 @@ IFS=$'\n'; for p_src in $(eval "find '${SRC_DIR}' \( -type f -o -type l \) \( -i
 
     esac
   fi
-  [ $? -ne 0 ] && echo "WARNING[$$]: An error occured while transcoding (${p_aux} -> ${p_dst}); skipping..." >&2 && continue
-   
-done
+}
+
+## Main
+
+# Check/create ID3 comment
+[ "${LAME_COMMENT}" == "#AUTO#" ] && LAME_COMMENT="Transcoded with ${0##*/} (${LAME_OPTS})"
+
+# Trap signals
+trap 'echo "INTERRUPT[${SCRIPT}($$)]: Cleaning and aborting" >&2; rm -f "${DST_LOCK}" "${p_dst}"; exit 2' INT TERM
+
+# Loop through audio files
+if [ -f "${SRC}" ]; then
+  p_src="${SRC}"
+  p_dst="${DST%.*}.mp3"
+
+  # Transcoding
+  if ! __transcode "${p_src}" "${p_dst}"; then
+    echo "ERROR[${SCRIPT}($$)]: An error occured while transcoding (${p_src} -> ${p_dst}); skipping..." >&2
+    exit 1
+  fi
+else
+  echo "INFO[${SCRIPT}($$)]: Looking for files to transcode..."
+  IFS=$'\n'
+  for p_src in $(eval "find '${SRC}' \( -type f -o -type l \) \( -iname '*.wav' -o -iname '*.mp3' ${AAC_INCL:+-o -iname '*.aac' -o -iname '*.m4a' -o -iname '*.mp4'} ${FLAC_INCL:+-o -iname '*.flac'} \)" | sort); do
+    # Compute source parameters
+    d_src="$(dirname "${p_src}")"
+    [ -e "${d_src}/.nodownsample" ] && continue
+
+    # Compute destination parameters
+    p_dst="${p_src%.*}.mp3"
+    p_dst="${DST}/${p_dst#${SRC}/}"
+    d_dst="$(dirname "${p_dst}")"
+
+    # Check/create destination directory
+    [ ! -d "${d_dst}" ] && mkdir -p "${d_dst}"
+    [ ! -d "${d_dst}" ] && echo "WARNING[${SCRIPT}($$)]: Failed to create destination directory (${d_dst}); skipping..." >&2 && continue
+    [ ! -w "${d_dst}" ] && echo "WARNING[${SCRIPT}($$)]: Unable to write to destination directory (${d_dst}): skipping..." >&2 && continue
+
+    # Check destination file
+    __atomic_begin
+    [ -e "${p_dst}" ] && __atomic_end && continue
+    touch "${p_dst}"
+    __atomic_end
+
+    # Transcoding
+    if ! __transcode "${p_src}" "${p_dst}"; then
+      echo "WARNING[${SCRIPT}($$)]: An error occured while transcoding (${p_src} -> ${p_dst}); skipping..." >&2
+      continue
+    fi
+  done
+fi
 
 # Done
-echo "INFO[$$]: Done"
+echo "INFO[${SCRIPT}($$)]: Done"
 exit 0
-
